version: "3.8"

services:
  mysqldb:
    image: mysql:5.7
    restart: unless-stopped
    env_file: ./.env
    environment:
      - MYSQL_ROOT_PASSWORD=$MYSQLDB_ROOT_PASSWORD
      - MYSQL_DATABASE=crud_boilerplate
    ports:
      - $MYSQLDB_LOCAL_PORT:$MYSQLDB_DOCKER_PORT
    expose:
      - $MYSQLDB_DOCKER_PORT
    volumes:
      - db:/var/lib/mysql

  client:
    build: ./client
    volumes:
      - ./client:/src/
      - node_modules_client:/src/node_modules
    ports:
      - "3000:3000"
    # environment:
    # CHOKIDAR_USEPOLLING: "true"

  server:
    depends_on:
      - mysqldb
    build: ./server
    # command: bash -c 'while !</var/lib/mysql/3306; do sleep 1; done; npm start'
    command: bash -c 'sleep 1; npm start'
    restart: unless-stopped
    env_file: ./.env
    ports:
      - $SERVER_NODE_LOCAL_PORT:$SERVER_NODE_DOCKER_PORT
    volumes:
      - ./server:/src/
      - node_modules_server:/src/node_modules
    environment:
      # CHOKIDAR_USEPOLLING: "true"
      - DB_HOST=$MYSQLDB_HOST
      - DB_USER=$MYSQLDB_USER
      - DB_PASSWORD=$MYSQLDB_ROOT_PASSWORD
      - DB_NAME=$MYSQLDB_DATABASE
      - DB_PORT=$MYSQLDB_DOCKER_PORT
    stdin_open: true
    tty: true

volumes:
  node_modules_client:
  node_modules_server:
  db:
